In [ ]:
# A1

In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile as zf

In [2]:
# Looking through the databases provided

# time_series code, date and value - US
bi_report_data = pd.read_csv("Business and Industry Report/data.csv.zip", low_memory=False)

# categories and descriptions, etc. - US
bi_report_metadata = pd.read_csv("Business and Industry Report/metadata.csv.zip", low_memory=False)

# US Industry codes and titles
naics_def = pd.read_csv("NAICS/2017 NAICS Definition.csv", low_memory=False)

# Monthly State Retail Sales for every industry from 01/20 to 05/20
mrtssales = pd.read_excel("NAICS/mrtssales92-present.xls")

# retail sales per NAICS (2012) and per product category - shows % of sales accounted for by industry
retail_sales = pd.read_csv("2012 Retail Sales by Store Type within Product Category.csv.zip", low_memory=False)

# Amazon Sales Report
amazon_sales = pd.read_csv("Amazon Sale Report.csv.zip", low_memory=False)

# Sample of 10000 items sold on amazon with reviews, ratings, etc.
amazon_sample = pd.read_csv("amazon_co-ecommerce_sample.csv.zip", low_memory=False)

# Australia Sales - lastest 2017-08-01
zf_aus = zf.ZipFile("AustraliaChains.xlsx.zip", "r")
aus_chains = pd.read_excel(zf_aus.open("AustraliaChains.xlsx"))

# CoF - city and country, x1,x2??
costofliving = pd.read_csv("cost-of-living_v2.csv", low_memory=False)

# countries are columns, info in rows (must be pivoted) with size and area
countries = pd.read_json("countries.json.zip")

# time_series_code, date and value (BOPGS_BAL_US_adj), might be the same as bi_report_data
bi_report_value = pd.read_csv("data.csv.zip",low_memory=False)

# data co supply chain - ERROR
zf_supply = zf.ZipFile("DataCoSupplyChainDataset.csv.zip")
datasupply = pd.read_csv(zf_supply.open("DataCoSupplyChainDataset.csv"),encoding='latin-1')

# Glassdoor Jobs
glassdoor = pd.read_csv("glassdoor_jobs.csv.zip",low_memory=False)

# International sale report - need a lot of cleaning, sku, international orders, rates, etc
intl_sales = pd.read_csv("International sale Report.csv.zip",low_memory=False)

# may 2022, retail prices in various sales channels
may_2022 = pd.read_csv("May-2022.csv",low_memory=False)

# time_series_code, date and value (BOPGS_BAL_US_adj), might be the same as bi_report_metadata
bi_report_metadata2 = pd.read_csv("metadata.csv",low_memory=False)

# nba players and MVP status, possible ambassadors
nba = pd.read_csv("NBA Finals and MVP.csv",low_memory=False)

# name, brand and sold by (w noon), old_price, current_price
noon = pd.read_csv("noon.csv",low_memory=False)

# sku code, designes, stocks, category, size, color
sku = pd.read_csv("Sale Report.csv",low_memory=False)

# transact no., date, productno, productname, price, quant, customerno, country
transact = pd.read_csv("Sales Transaction v.4a.csv",low_memory=False)

# zara scraped sample with sales data
zara_sample = pd.read_json("zara_us_sample_data.json.zip")

In [3]:
countries.head(10)

,Afghanistan,Akrotiri,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antarctica,Antigua and Barbuda,...,Venezuela,Vietnam,Virgin Islands,Wake Island,Wallis and Futuna,West Bank,World,Yemen,Zambia,Zimbabwe
url,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...,https://www.cia.gov/the-world-factbook/countri...
Introduction: Background,Ahmad Shah DURRANI unified the Pashtun tribes ...,By terms of the 1960 Treaty of Establishment t...,Albania declared its independence from the Ott...,Algeria has known many empires and dynasties s...,Tutuila was settled by 1000 B.C. and the islan...,The Moorish invasion of Spain in the 8th centu...,From the late 14th to the mid 19th century a K...,Colonized by English settlers from Saint Kitts...,"Speculation over the existence of a ""southern ...",The Siboney were the first people to inhabit t...,...,Venezuela was one of three countries that emer...,Ancient Vietnam was centered on the Red River ...,The Danes secured control over the southern Vi...,Wake Island was probably visited by Micronesia...,The first humans settled Wallis and Futuna aro...,The landlocked West Bank - the larger of the t...,"Globally, the 20th century was marked by: (a) ...",The Kingdom of Yemen (colloquially known as No...,Multiple waves of Bantu-speaking groups moved ...,The hunter-gatherer San people first inhabited...
Geography: Location,"Southern Asia, north and west of Pakistan, eas...","Eastern Mediterranean, peninsula on the southw...","Southeastern Europe, bordering the Adriatic Se...","Northern Africa, bordering the Mediterranean S...","Oceania, group of islands in the South Pacific...","Southwestern Europe, Pyrenees mountains, on th...","Southern Africa, bordering the South Atlantic ...","Caribbean, islands between the Caribbean Sea a...",continent mostly south of the Antarctic Circle,"Caribbean, islands between the Caribbean Sea a...",...,"Northern South America, bordering the Caribbea...","Southeastern Asia, bordering the Gulf of Thail...","Caribbean, islands between the Caribbean Sea a...","Oceania, atoll in the North Pacific Ocean, abo...","Oceania, islands in the South Pacific Ocean, a...","Middle East, west of Jordan, east of Israel",NaN,"Middle East, bordering the Arabian Sea, Gulf o...","Southern Africa, east of Angola, south of the ...","Southern Africa, between South Africa and Zambia"
Geography: Geographic coordinates,"33 00 N, 65 00 E","34 37 N, 32 58 E","41 00 N, 20 00 E","28 00 N, 3 00 E","14 20 S, 170 00 W","42 30 N, 1 30 E","12 30 S, 18 30 E","18 15 N, 63 10 W","90 00 S, 0 00 E","17 03 N, 61 48 W",...,"8 00 N, 66 00 W","16 10 N, 107 50 E","18 20 N, 64 50 W","19 17 N, 166 39 E","13 18 S, 176 12 W","32 00 N, 35 15 E",NaN,"15 00 N, 48 00 E","15 00 S, 30 00 E","20 00 S, 30 00 E"
Geography: Map references,Asia,Middle East,Europe,Africa,Oceania,Europe,Africa,Central America and the Caribbean,Antarctic Region,Central America and the Caribbean,...,South America,Southeast Asia,Central America and the Caribbean,Oceania,Oceania,Middle East,Physical Map of the World,Middle East,Africa,Africa
Geography: Area - total,"652,230 sq km",123 sq km,"28,748 sq km","2,381,740 sq km",224 sq km,468 sq km,"1,246,700 sq km",91 sq km,14.2 million sq km,443 sq km (Antigua 280 sq km; Barbuda 161 sq km),...,"912,050 sq km","331,210 sq km","1,910 sq km",7 sq km,142 sq km,"5,860 sq km",510.072 million sq km,"527,968 sq km","752,618 sq km","390,757 sq km"
Geography: Area - land,"652,230 sq km",NaN,"27,398 sq km","2,381,740 sq km",224 sq km,468 sq km,"1,246,700 sq km",91 sq km,"14.2 million sq km (285,000 sq km ice-free, 13...",443 sq km,...,"882,050 sq km","310,070 sq km",346 sq km,6.5 sq km,142 sq km,"5,640 sq km",148.94 million sq km,"527,968 sq km","743,398 sq km","386,847 sq km"
Geography: Area - water,0 sq km,NaN,"1,350 sq km",0 sq km,0 sq km,0 sq km,0 sq km,0 sq km,NaN,0 sq km,...,"30,000 sq km","21,140 sq km","1,564 sq km",0 sq km,0 sq km,220 sq km,361.9 million sq km,0 sq km,"9,220 sq km","3,910 sq km"
Geography: Area - comparative,almost six times the size of Virginia; slightl...,"about 0.7 times the size of Washington, DC",slightly smaller than Maryland,slightly less than 3.5 times the size of Texas,"slightly larger than Washington, DC","2.5 times the size of Washington, DC",about eight times the size of Georgia; slightl...,"about one-half the size of Washington, DC",slightly less than 1.5 times the size of the US,"2.5 times the size of Washington, DC",...,almost six times the size of Georgia; slightly...,about three times the size of Tennessee; sligh...,"twice the size of Washington, DC",about 11 times the size of the National Mall i...,"1.5 times the size of Washington, DC",slightly smaller than Delaware,land area about 16 times the size of the US,almost four times the size of Alabama; slightl...,almost five times the size of Georgia; slightl...,about four times the size of Indiana; slightly...
Geography: Land boundaries - total,"5,987 km",48 km,691 km,"6,734 km",0 km,118 km,"5,369 km",0 km,NaN,0 km,...,"5,267 km","4,616 km",0 km,0 km,0 km,478 km,NaN,"1,601 km","6,043.15 km","3,229 km"

In [79]:
# Files related to CONSUMER PRICE INDEX

zf_cpi = zf.ZipFile("untitled folder/Consumer Price Index.zip") 

# Area Codes used to section CPIs
cpi_area = pd.read_csv(zf_cpi.open("cu.area.csv"), low_memory=False)

# Base Code used to section CPIs
cpi_base = pd.read_csv(zf_cpi.open("cu.base.csv"), low_memory=False)

# Item code used in CPI
cpi_item = pd.read_csv(zf_cpi.open("cu.item.csv"), low_memory=False)

# Footnote in CPI - EMPTY
cpi_footnote = pd.read_csv(zf_cpi.open("cu.footnote.csv"), low_memory=False)

# Period Codes for CPI calculation, monthly and semi-annual (half-year), annual averages
cpi_period = pd.read_csv(zf_cpi.open("cu.period.csv"), low_memory=False)

# Periodicity Code: R = Monthly, S = Semi
cpi_periodicity = pd.read_csv(zf_cpi.open("cu.periodicity.csv"), low_memory=False)

# Serieses, per area, per season, per item
cpi_series = pd.read_csv(zf_cpi.open("cu.series.csv"), low_memory=False)

# Series organized per year, per period with VALUES - latest 2017, Current?
cpidata_0 = pd.read_csv(zf_cpi.open("cu.data.0.Current.csv"), low_memory=False)

# Series organized per year, per period with VALUES - latest 2017, All Items
cpidata_1 = pd.read_csv(zf_cpi.open("cu.data.1.AllItems.csv"), low_memory=False)

# Series organized per year, per period with VALUES - latest 2017, Summaries
cpidata_2 = pd.read_csv(zf_cpi.open("cu.data.2.Summaries.csv"), low_memory=False)

# Series organized per year, per period with VALUES - latest 2017, AsizeNorthEast
cpidata_3 = pd.read_csv(zf_cpi.open("cu.data.3.AsizeNorthEast.csv"), low_memory=False)

# Series organized per year, per period with VALUES - latest 2017, AsizeNorthCentral
cpidata_4 = pd.read_csv(zf_cpi.open("cu.data.4.AsizeNorthCentral.csv"), low_memory=False)

In [80]:
cpidata_4.head(10)

     series_id  year period  value  footnote_codes
0  CUURA200AA0  1977    M12  100.0             NaN
1  CUURA200AA0  1978    M02  101.4             NaN
2  CUURA200AA0  1978    M04  103.4             NaN
3  CUURA200AA0  1978    M06  105.3             NaN
4  CUURA200AA0  1978    M08  106.5             NaN
5  CUURA200AA0  1978    M10  108.7             NaN
6  CUURA200AA0  1978    M12  110.1             NaN
7  CUURA200AA0  1978    M13  105.5             NaN
8  CUURA200AA0  1979    M02  112.7             NaN
9  CUURA200AA0  1979    M04  115.7             NaN

In [ ]:
# World Bank Data

zf_wb = zf.ZipFile("World Bank.zip")

In [ ]:
# I don't understand these

# May be related to India? may 2022, retail prices in various sales channels
r_may_2022 = pd.read_csv("May-2022.csv",low_memory=False)

# May be related to India? sku code, designes, stocks, category, size, color
r_sku = pd.read_csv("Sale Report.csv",low_memory=False)

# Includes products that are not clothing? transact no., date, productno, productname, price, quant, customerno, country
r_sales_txn = pd.read_csv("Sales Transaction v.4a.csv",low_memory=False)

In [ ]:
#FOR HOLDING

# India Clothing Retail Sales (From Amazon)
r_india_amazon = pd.read_csv("Amazon Sale Report.csv.zip", low_memory=False)
# UAE Clothing Retail Sales (From Noon, Nanshi, SIVVI)
r_uae_noon = pd.read_csv("noon.csv",low_memory=False)
# Australia Clothing Sales - latest 2017-08-01
zf_aus = zf.ZipFile("AustraliaChains.xlsx.zip", "r")
r_aus_chains = pd.read_excel(zf_aus.open("AustraliaChains.xlsx"))
# US Clothing Sales - Zara
r_us_zara = pd.read_json("zara_us_sample_data.json.zip")

In [9]:
# time_series code, date and value - US
zf_wb = zf.ZipFile("World Bank.zip")
r_ind = pd.read_csv(zf_wb.open("world-development-indicators/Indicators.csv"),low_memory=False)
r_ser = pd.read_csv(zf_wb.open("world-development-indicators/Series.csv"),low_memory=False)

r_ser["Topic"].str.contains("inflation")

0       False
1       False
2       False
3       False
4       False
        ...
1340    False
1341    False
1342    False
1343    False
1344    False
Name: Topic, Length: 1345, dtype: bool