In [1]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile as zf

In [7]:
zf_wb = zf.ZipFile("World Bank.zip")

# cost of living 2020
wb_costofliving = pd.read_csv(zf_wb.open("2020-cost-of-living/cost of living 2020.csv"),low_memory=False)

# Countries_and_continents_of_the_world
wb_countriescont = pd.read_csv(zf_wb.open("Countries_and_continents_of_the_world.csv"),low_memory=False)

In [9]:
wb_countriescont.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Data columns (total 51 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   temp_coldestQuart                   236 non-null    float64
 1   temp_driestQuart                    236 non-null    float64
 2   Agriculture                         211 non-null    object
 3   Country Name                        269 non-null    object
 4   Net migration                       223 non-null    object
 5   Coastline (coast/area ratio)        226 non-null    object
 6   Capital                             243 non-null    object
 7   accessibility_to_cities             237 non-null    float64
 8   Population 2020                     46 non-null     float64
 9   Population                          226 non-null    float64
 10  Climate_short_desc                  204 non-null    object
 11  temp_annual_range                   236 non-null    float64
 12  elevation                           235 non-null    float64
 13  Phones (per 1000)                   222 non-null    object
 14  Continent                           269 non-null    object
 15  Development Status                  269 non-null    object
 16  Climate_index                       204 non-null    object
 17  Literacy (%)                        208 non-null    object
 18  temp_diurnal_range                  236 non-null    float64
 19  latitude                            269 non-null    float64
 20  temp_warmestQuart                   236 non-null    float64
 21  Birthrate                           223 non-null    object
 22  official_name_en                    239 non-null    object
 23  Service                             211 non-null    object
 24  Human Asset Index                   132 non-null    float64
 25  Country Code                        268 non-null    object
 26  Human Development Index             185 non-null    float64
 27  Infant mortality (per 1000 births)  223 non-null    object
 28  Languages                           246 non-null    object
 29  temp_min_coldestMonth               236 non-null    float64
 30  is_independent                      249 non-null    object
 31  temp_max_warmestMonth               236 non-null    float64
 32  longitude                           269 non-null    float64
 33  temp_mean_annual                    236 non-null    float64
 34  temp_wettestQuart                   236 non-null    float64
 35  ISO4217-currency_name               235 non-null    object
 36  GNI per capita                      144 non-null    object
 37  wind                                187 non-null    float64
 38  Climate_long_desc                   204 non-null    object
 39  GDP ($ per capita)                  225 non-null    float64
 40  Deathrate                           222 non-null    object
 41  cloudiness                          233 non-null    float64
 42  geonumber                           265 non-null    float64
 43  Region                              269 non-null    object
 44  Pop. Density (per sq. mi.)          226 non-null    object
 45  temp_seasonality                    236 non-null    float64
 46  Area (sq. mi.)                      226 non-null    float64
 47  Geoname ID                          249 non-null    float64
 48  Industry                            210 non-null    object
 49  climate_additional_description      242 non-null    object
 50  climate                             269 non-null    object
dtypes: float64(24), object(27)
memory usage: 107.3+ KB

In [8]:
wb_countriescont.head(10)

,temp_coldestQuart,temp_driestQuart,Agriculture,Country Name,Net migration,Coastline (coast/area ratio),Capital,accessibility_to_cities,Population 2020,Population,...,cloudiness,geonumber,Region,Pop. Density (per sq. mi.),temp_seasonality,Area (sq. mi.),Geoname ID,Industry,climate_additional_description,climate
0,-0.261352,21.120329,"0,38",Afghanistan,"23,06","0,00",Kabul,317.715752,NaN,31056997.0,...,114.228983,22376.749753,ASIA (EX. NEAR EAST),"48,0",88.153515,647500.0,1149361.0,"0,24",arid to semiarid; cold winters and hot summers,Warm Temperate/Mediterranean
1,-4.101205,-1.280922,NaN,Aland Islands,NaN,NaN,Mariehamn,235.068864,NaN,NaN,...,NaN,27052.050057,WESTERN EUROPE,NaN,72.670694,NaN,661882.0,NaN,NaN,Cool/Taiga/Siberian Temperate
2,3.579896,19.573206,"0,232",Albania,"-4,93","1,26",Tirana,73.830856,NaN,3581655.0,...,181.131113,23627.768091,EASTERN EUROPE,"124,6",62.668515,28748.0,783754.0,"0,188","mild temperate; cool, cloudy, wet winters; hot...",Temperate Grasslands/Steppe
3,13.151553,26.921072,"0,101",Algeria,"-0,39","0,04",Algiers,1212.799818,NaN,32930091.0,...,90.674395,21247.759106,NORTHERN AFRICA,"13,8",75.110263,2381740.0,2589581.0,"0,6","arid to semiarid; mild, wet winters with hot, ...",Hot/Mid-Latitude Desert
4,25.696020,25.859011,NaN,American Samoa,"-20,71","58,29",Pago Pago,323.064327,NaN,57794.0,...,256.029854,13461.092823,OCEANIA,"290,4",4.975535,199.0,5880801.0,NaN,"tropical marine, moderated by southeast trade ...",Savana/Sudan
5,-1.989975,4.336232,NaN,Andorra,"6,6","0,00",Andorra la Vella,85.971636,77265.0,71201.0,...,179.093247,23852.653101,WESTERN EUROPE,"152,1",54.196351,468.0,3041565.0,NaN,"temperate; snowy, cold winters and warm, dry s...",Temperate Grasslands/Steppe
6,18.793516,18.866882,"0,096",Angola,0,"0,13",Luanda,378.202392,NaN,12127071.0,...,187.517044,14201.389327,SUB-SAHARAN AFRICA,"9,7",18.535815,1246700.0,3351879.0,"0,658",semiarid in south and along coast to Luanda; n...,Savana/Sudan
7,25.493355,25.886688,"0,04",Anguilla,"10,76","59,80",The Valley,762.500000,NaN,13477.0,...,198.976514,19416.631105,LATIN AMER. & CARIB,"132,1",11.371226,102.0,3573511.0,"0,18",tropical; moderated by northeast trade winds,Savana/Sudan
8,NaN,NaN,NaN,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,...,302.807829,1419.704640,ANTARTICA,NaN,NaN,NaN,6697173.0,NaN,"severe low temperatures vary with latitude, el...",Arctic/Polar/Tundra
9,24.723990,25.226852,"0,038",Antigua & Barbuda,"-6,15","34,54",St. John's,309.905556,NaN,69108.0,...,195.127621,19209.150452,LATIN AMER. & CARIB,"156,0",11.256880,443.0,3576396.0,"0,22",tropical maritime; little seasonal temperature...,Savana/Sudan

In [ ]:
zf_aus = zf.ZipFile("AustraliaChains.xlsx.zip", "r")
aus_chains = pd.read_excel(zf_aus.open("AustraliaChains.xlsx"))